"""create schema

Revision ID: 3d290c98766b
Revises: 
Create Date: 2025-02-13 16:23:27.140788

"""
from typing import Sequence, Union
from sqlalchemy import Column, INTEGER, VARCHAR, Boolean, ForeignKey, TIMESTAMP, func

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3d290c98766b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        Column('id', INTEGER, primary_key=True, index=True),
        Column('name', VARCHAR(30), unique=True, nullable=False),
        Column('permissions', VARCHAR(1024)),  # Store permissions as CSV
    )
    op.bulk_insert(
        'roles',
        [
            {'name': 'admin', 'permissions': 'create_users,read_users,update_users,delete_users'},
            {'name': 'manager', 'permissions': 'read_users,update_users'},
            {'name': 'user', 'permissions': ''},
        ]
    )
    op.create_table(
        'users',
        Column('id', INTEGER, primary_key=True, index=True),
        Column('username', VARCHAR(30), unique=True, index=True, nullable=False),
        Column('email', VARCHAR(30), unique=True, index=True, nullable=False),
        Column('hashed_password', VARCHAR(255)),
        Column('is_active', Boolean, default=True),
        Column('role_id', INTEGER, ForeignKey("roles.id")),
        Column('created_at', TIMESTAMP, server_default=func.now()),
        Column('updated_at', TIMESTAMP, server_default=func.now(), onupdate=func.now()),
    )


def downgrade() -> None:
    op.drop_table('users')
    op.drop_table('roles')
